#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Rodar o phpstan
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "Opss... deu erro no phpstan, corrija antes de continuar!!! 😉"
    exit 1;
fi

# Formatar cada arquivo alterado usando Laravel Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGE_FILES
do
    ./vendor/bin/pint "${FILE}";
    git add "${FILE}";
done;

exit 0;
